In [1]:
import tensorflow.compat.v1 as tf
import numpy as np
#import matplotlib.image as mpimg
from PIL import Image

In [2]:
import AlexNet

In [3]:
model = AlexNet.AlexNet2(trainable=False)

In [4]:
image = Image.open(r"picture\poodle.png")
type(image)
'''
im1 = (imread(r"picture\poodle.png")[:,:,:3]).astype(np.float32)
im1 = im1 - np.mean(im1)
im1[:, :, 0], im1[:, :, 2] = im1[:, :, 2], im1[:, :, 0]'''

'\nim1 = (imread(r"picture\\poodle.png")[:,:,:3]).astype(np.float32)\nim1 = im1 - np.mean(im1)\nim1[:, :, 0], im1[:, :, 2] = im1[:, :, 2], im1[:, :, 0]'

In [41]:
image1= np.array(image).astype(np.float32)
image2 = image1[:,:,:3]

In [40]:
image3 = image2 - np.mean(image2)
image3

array([[[ -9.336609 ,  -7.336609 ,  -9.336609 ],
        [ -8.336609 ,  -6.336609 ,  -6.336609 ],
        [ -8.336609 ,  -7.336609 ,  -4.336609 ],
        ...,
        [ 12.663391 ,   9.663391 ,   4.663391 ],
        [ 14.663391 ,   9.663391 ,   7.663391 ],
        [ 14.663391 ,  11.663391 ,   5.663391 ]],

       [[  2.663391 ,   4.663391 ,   0.6633911],
        [ -4.336609 ,  -2.336609 ,  -6.336609 ],
        [  9.663391 ,  11.663391 ,  10.663391 ],
        ...,
        [  8.663391 ,   7.663391 ,   5.663391 ],
        [  7.663391 ,   7.663391 ,   5.663391 ],
        [  8.663391 ,   7.663391 ,   3.663391 ]],

       [[ 25.663391 ,  26.663391 ,  21.663391 ],
        [ 19.663391 ,  20.663391 ,  15.663391 ],
        [ 18.663391 ,  19.663391 ,  14.663391 ],
        ...,
        [  4.663391 ,   4.663391 ,   4.663391 ],
        [  3.663391 ,   3.663391 ,   3.663391 ],
        [ -0.3366089,  -0.3366089,  -2.336609 ]],

       ...,

       [[-25.336609 , -20.336609 , -17.336609 ],
        [-1

In [7]:
config = tf.ConfigProto() 
config.gpu_options.allow_growth=True
config.gpu_options.per_process_gpu_memory_fraction = 0.4  #占用40%显存
sess = tf.Session(config=config)
saver = tf.train.Saver()
saver.restore(sess, 'ckpt/my_alexnet')

W1020 18:36:01.975589  1336 deprecation.py:323] From D:\anaconda\envs\tensorflow1.14\lib\site-packages\tensorflow\python\training\saver.py:1276: checkpoint_exists (from tensorflow.python.training.checkpoint_management) is deprecated and will be removed in a future version.
Instructions for updating:
Use standard file APIs to check for files with this prefix.


In [8]:
im1 = image3.reshape([-1, 227, 227, 3])
im1.shape

(1, 227, 227, 3)

In [54]:
output = tf.get_default_graph().get_operation_by_name('first_conv_layer_part1/BiasAdd')
output2 = output.outputs[0]

In [55]:
value=sess.run(output2[0], feed_dict={model.input_x: im1})

In [26]:
variable1 = tf.get_default_graph().get_tensor_by_name('first_conv_layer_part1/kernel_bias:0')

In [56]:
print(value)

[[[-1.10268402e+00 -3.20483551e+01  2.12042580e+01 ... -1.48631163e+01
    1.01266298e+01 -3.48338544e-01]
  [ 4.70879936e+00 -7.77621841e+00  1.01575823e+01 ... -7.49351072e+00
    5.03844547e+00 -9.06182826e-01]
  [-6.73593998e-01 -1.65937881e+01  1.58319073e+01 ...  8.94460082e-02
   -2.84996182e-01  5.90685987e+00]
  ...
  [-6.85947180e-01 -4.21462173e+01 -4.27603817e+00 ...  2.47963548e+00
    8.14347076e+00  1.67325172e+01]
  [ 2.33977437e+00  1.84017813e+00 -8.94118786e+00 ...  1.83340049e+00
    3.26671314e+00  1.75168819e+01]
  [-5.01206064e+00 -2.43922367e+01  7.91442156e+00 ...  3.87943649e+00
    2.57440519e+00  1.73581467e+01]]

 [[ 4.42348123e-02 -3.84629135e+01 -5.36383533e+00 ... -1.00420084e+01
    1.39524431e+01  9.73215580e+00]
  [ 1.26360226e+00 -2.20942249e+01 -1.04057751e+01 ...  3.31194592e+00
   -3.33088279e+00  8.52737045e+00]
  [ 5.42230606e+00  2.11462612e+01 -7.53164864e+00 ... -1.19208050e+00
   -5.78969121e-02  6.26378345e+00]
  ...
  [-1.84573007e+00 -7.6

In [11]:
index = np.argsort(value)[-5:]

In [12]:
index

array([228, 181, 267, 265, 266], dtype=int64)

In [13]:
value[index]

array([0.05748022, 0.13473406, 0.1687309 , 0.2247034 , 0.3658793 ],
      dtype=float32)

In [22]:
sess.close()